### ISSUE TITLE
zsh: exec format error: ./makedepf90

### ISSUE THREAD

**Issue by marc-shen** [PrincetonUniversity/tristan-mp-v2#15]
I got this error when I tried to compile on my computer.
```
zsh: exec format error: ./makedepf90
```
My computer configuration is an ARM architecture Mac Book pro with M1 chip.

The configuration file was made by this command `python configure.py -mpi -hdf5 --user=user_2d_rec -2d`.

**Comment by haykh** [comment]
`makedepf90` is a binary which creates a dependency tree (this has been done to avoid explicitly enumerating all the file dependencies). the reason it's included as a binary (which is compiled on x86 architectures) is because i simply could not find the workable source code for it. there is a duplicated source code [here](https://github.com/outpaddling/makedepf90), but i weren't able to properly compile it. 

the best option by far would be to rewrite the configuration using `cmake`, at some point i'll do that, but for now we rely on `makedepf90`. if you are able to compile the `makedepf90` -- let me know, i'll include it in the code.

**Comment by marc-shen** [comment]
I have solved the `makedepf90` compile issue.

https://github.com/amckinstry/makedepf90

I used this  repository to compile on the arm64 architectures.

**Comment by marc-shen** [comment]
But there are some problems else.
https://github.com/PrincetonUniversity/tristan-mp-v2/issues/18

**Comment by haykh** [comment]
see #18 for possible solution also with the `makedepf90` (`CMake` support added)
